export const specifications = [
    {
      id: "0",
      logo: "/src/assets/corpo.png",
      NameTitle: "НАЗВА",
      NameDescription: "КіберШок",
      Backstory: "ІСТОРІЯ",
      BackstoryTitle: "Корпар",
      BackstoryDescription: "Подейкують, що він носить у собі дух творця.",
      Difficulty: "ТАРИФ",
      DifficultyDescription: "130 грн/год",
      AttributesTitle: "ТЕХНІЧНІ ХАРАКТЕРИСТИКИ",
      BodyText: "64 GB DDR5",
      BodyValue: "RAM",
      IntelligenceText: "INTEL CORE i9",
      IntelligenceValue: "CPU",
      ReflexText: "RTX 4090",
      ReflexValue: "GPU",
      TechAbilText: "",
      TechAbilValue: "SSD",
      CoolText: "",
      CoolValue: "",
    },
    {
      id: "1",
      logo: "/src/assets/nomad.png",
      NameTitle: "НАЗВА",
      NameDescription: "Матричний Мародер",
      Backstory: "ІСТОРІЯ",
      BackstoryTitle: "Кочівник",
      BackstoryDescription: "Універсальний інструмент для найманців у тінях.",
      Difficulty: "ТАРИФ",
      DifficultyDescription: "60 грн/год",
      AttributesTitle: "ТЕХНІЧНІ ХАРАКТЕРИСТИКИ",
      BodyText: "16 GB DDR4",
      BodyValue: "RAM",
      IntelligenceText: "INTEL CORE i5",
      IntelligenceValue: "CPU",
      ReflexText: "RTX 4060 Ti",
      ReflexValue: "GPU",
      TechAbilText: "",
      TechAbilValue: "SSD",
      CoolText: "",
      CoolValue: "",
    },
    {
      id: "2",
      logo: "/src/assets/streetkid.png",
      NameTitle: "НАЗВА",
      NameDescription: "Хромова Лихоманка",
      Backstory: "ІСТОРІЯ",
      BackstoryTitle: "Дитя вулиць",
      BackstoryDescription: "Розроблений для елітної кібернетичної війни.",
      Difficulty: "ТАРИФ",
      DifficultyDescription: "90 грн/год",
      AttributesTitle: "ТЕХНІЧНІ ХАРАКТЕРИСТИКИ",
      BodyText: "32 GB DDR4",
      BodyValue: "RAM",
      IntelligenceText: "INTEL CORE i7",
      IntelligenceValue: "CPU",
      ReflexText: "RTX 4080",
      ReflexValue: "GPU",
      TechAbilText: "",
      TechAbilValue: "SSD",
      CoolText: "",
      CoolValue: "",
    },
]