export const specifications = [
    {
      id: "0",
      logo: "/src/assets/corpo.png",
      NameTitle: "НАЗВА",
      NameDescription: "КіберШок",
      Backstory: "ІСТОРІЯ",
      Room: "ЗАЛ",
      RoomTitle: "Корпар",
      BackstoryDescription: "Подейкують, що він носить у собі дух творця.",
      Difficulty: "ТАРИФ",
      DifficultyDescription: "130 грн/год",
      AttributesTitle: "ТЕХНІЧНІ ХАРАКТЕРИСТИКИ",
      BodyText: "64 GB DDR5",
      BodyValue: "RAM",
      IntelligenceText: "INTEL CORE i9",
      IntelligenceValue: "CPU",
      ReflexText: "RTX 4090",
      ReflexValue: "GPU",
      TechAbilText: "",
      TechAbilValue: "ОКРЕМА КІМНАТА",
      CoolText: "",
      CoolValue: "",
    },
    {
      id: "1",
      logo: "/src/assets/nomad.png",
      NameTitle: "НАЗВА",
      NameDescription: "Матричний Мародер",
      Backstory: "ІСТОРІЯ",
      BackstoryDescription: "Універсальний інструмент для найманців у тінях.",
      Room: "ЗАЛ",
      RoomTitle: "Кочівник",
      Difficulty: "ТАРИФ",
      DifficultyDescription: "60 грн/год",
      AttributesTitle: "ТЕХНІЧНІ ХАРАКТЕРИСТИКИ",
      BodyText: "16 GB DDR4",
      BodyValue: "RAM",
      IntelligenceText: "INTEL CORE i5",
      IntelligenceValue: "CPU",
      ReflexText: "RTX 4060 Ti",
      ReflexValue: "GPU",
      TechAbilText: "",
      TechAbilValue: "ЗАГАЛЬНИЙ ЗАЛ",
      CoolText: "",
      CoolValue: "",
    },
    {
      id: "2",
      logo: "/src/assets/streetkid.png",
      NameTitle: "НАЗВА",
      NameDescription: "Хромова Лихоманка",
      Backstory: "ІСТОРІЯ",
      BackstoryDescription: "Розроблений для елітної кібернетичної війни.",
      Room: "ЗАЛ",
      RoomTitle: "Дитя вулиць",
      Difficulty: "ТАРИФ",
      DifficultyDescription: "90 грн/год",
      AttributesTitle: "ТЕХНІЧНІ ХАРАКТЕРИСТИКИ",
      BodyText: "32 GB DDR4",
      BodyValue: "RAM",
      IntelligenceText: "INTEL CORE i7",
      IntelligenceValue: "CPU",
      ReflexText: "RTX 4080",
      ReflexValue: "GPU",
      TechAbilText: "",
      TechAbilValue: "ОКРЕМА КІМНАТА",
      CoolText: "",
      CoolValue: "ДЛЯ 5 ГРАВЦІВ",
    },
]

export const peripheralsCol1 = ['Монітор', 'Миша', 'Клавіатура', 'Гарнітура', 'Крісло']

export const peripheralsCol2Nomad = [
  "Asus 24' 165 Hz",
  'Hator Vortex EVO',
  'Hator Rockfall EVO TKL',
  'Hator Hypergang EVO',
  'Hator Sport Essential',
]

export const peripheralsCol2Streetkid = [
  "Asus 24' 165 Hz",
  'Razer Death Adder V2',
  'Razer BlackWidow V3 TKL',
  'Razer Black Shark V2 X',
  'Hator Sport Essential',
]

export const peripheralsCol2Corpo = [
  "Asus 27' 280 Hz",
  'HyperX Pulsefire Surge',
  'HyperX Alloy Origins',
  'HyperX Alpha S',
  'DX Racer D8100',
]